data:
  животные: [кот, пес, слон, лев, жираф, кенгуру, пантера, бегемот, утконос, хамелеон, коала, броненосец]
  еда: [хлеб, сыр, суп, рис, паста, пицца, салат, суши, эклер, ризотто, бранч, круассан]
  города: [Москва, Париж, Лондон, Рим, Стамбул, Берлин, Мадрид, Токио, Стокгольм, Амстердам, Барселона, Прага]
